backend:
  name: git-gateway
  branch: main

site_url: https://baumschule-zimmern.de/

media_folder: "src/assets/img/uploads"

public_folder: "/assets/img/uploads"

publish_mode: editorial_workflow

logo_url: "/assets/img/zimmern_logo.png"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "ausbildung"
    label: "Stellenanzeige Ausbildung"
    folder: "src/ausbildung"
    slug: "{{ausschreibung-ausbildung}}"
    create: true
    fields:
      - {label: "Ausschreibung Ausbildung", name: "ausschreibung-ausbildung", widget: "string"}


  - name: "berufserfahrene"
    label: "Stellenanzeige Berufserfahrene"
    folder: "src/berufserfahrene"
    slug: "{{ausschreibung-berufserfahrene}}"
    create: true
    fields:
      - {label: "Ausschreibung Berufserfahrene", name: "ausschreibung-berufserfahrene", widget: "string"}
