backend:
  name: git-gateway
  branch: main

site_url: https://baumschule-zimmern.de/

media_folder: "src/assets/img/galleries"

public_folder: "/assets/img/galleries"

publish_mode: editorial_workflow

logo_url: "/assets/img/zimmern_logo.png"

collections:
  - name: "ausbildung"
    label: "Stellenanzeige Ausbildung"
    folder: "src/karriere-ausbildung-ausschreibung"
    slug: "{{fields.slug}}"
    preview_path: karriere-ausbildung-ausschreibung/{{slug}}
    create: true
    fields:
      - {label: "Ausschreibung Ausbildung", name: "ausschreibung_ausbildung", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}


  - name: "berufserfahrene"
    label: "Stellenanzeige Berufserfahrene"
    folder: "src/karriere-berufserfahrene-ausschreibung"
    slug: "{{fields.slug}}"
    preview_path: karriere-berufserfahrene-ausschreibung/{{slug}}
    create: true
    fields:
      - {label: "Ausschreibung Berufserfahrene", name: "ausschreibung_berufserfahrene", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}


  - name: "projektgalerie"
    label: "Projektgalerie"
    fields:
      - label: "Galerie-Filter"
        name: "filter"
        widget: "select"
        required: true
        options: 
          - gartenneubau
          - baumpflege
          - gartenpflege
          - baumschule
          - baufelderschliessung
          - ideeberatungplanung

      - label: "Galerie Image"
        name: "galerie-image"
        widget: "image"
        folder: src/assets/img/galleries
        create: true
        choose_url: false
        media_library:
          config:
            multiple: false

