backend:
  name: git-gateway
  branch: main

site_url: https://baumschule-zimmern.de/

media_folder: "src/assets/img/uploads"

public_folder: "/assets/img/uploads"

publish_mode: editorial_workflow

logo_url: "/assets/img/zimmern_logo.png"

collections:
  - name: "ausbildung"
    label: "Stellenanzeige Ausbildung"
    folder: "src/ausbildung"
    preview_path: "ausbildung/{{slug}}"
    create: true
    fields:
      - {label: "Ausschreibung Ausbildung", name: "ausschreibung_ausbildung", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}


  - name: "berufserfahrene"
    label: "Stellenanzeige Berufserfahrene"
    folder: "src/berufserfahrene"
    preview_path: "berufserfahrene/{{slug}}"
    create: true
    fields:
      - {label: "Ausschreibung Berufserfahrene", name: "ausschreibung_berufserfahrene", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
